'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace APIAsynch

    Partial Public Class TAB_TAREA_ROW
        Public Property id_row As Long
        Public Property num_renglon As Integer
        Public Property id_tarea As Long
        Public Property llamada_api As String
        Public Property resultado_api As String
    
    End Class

End Namespace
