'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace APIAsynch

    Partial Public Class TAB_TAREA
        Public Property id_tarea As Long
        Public Property id_archivo As Long
        Public Property total_lineas As Long
        Public Property lineas_procesadas As Nullable(Of Long)
        Public Property geo1 As Nullable(Of Byte)
        Public Property geo2 As Nullable(Of Byte)
        Public Property blitz1 As Nullable(Of Byte)
        Public Property blitz2 As Nullable(Of Byte)
        Public Property blitz3 As Nullable(Of Byte)
    
    End Class

End Namespace
