'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace APIAsynch

    Partial Public Class nmmxEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=nmmxEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property TAB_TAREA() As DbSet(Of TAB_TAREA)
        Public Overridable Property TAB_TAREA_ROW() As DbSet(Of TAB_TAREA_ROW)
    
    End Class

End Namespace
