'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmMarketing

    '''<summary>
    '''hfLIFsProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLIFsProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLIFsOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLIFsOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAssignedProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAssignedProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAssignedOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAssignedOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfNotAssignedProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNotAssignedProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfNotAssignedOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNotAssignedOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAssignationRateProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAssignationRateProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAssignationRateOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAssignationRateOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtLifsOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLifsOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtLifsProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLifsProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtAssignedOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignedOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtAssignedProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignedProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtVisitedOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVisitedOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtVisitedProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVisitedProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCompletedOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompletedOB As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCompletedProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompletedProp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dropDownCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropDownCampaigns As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''mesesJSON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mesesJSON As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''totalMerchants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalMerchants As Global.System.Web.UI.WebControls.HiddenField
End Class
